services:
  backend:
    image: seesun-backend:latest
    container_name: seesun-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
        TZ: Asia/Seoul
    volumes:
      - /home/ubuntu/app/config/application-secret.yml:/app/config/application-secret.yml:ro
      - /home/ubuntu/app/files:/app/files